### ISSUE TITLE
Unable to deploy/build node web app 

### ISSUE THREAD

**Issue by kayvear** [microsoft/Oryx#1204] opened 2022-01-14 20:37 UTC
### Bug Report

- At what date and time did you most recently experience the problem?
01/14/2022 15:20 EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
No, its on my local git. 

- What happened?
When I push my node app from local git to Azure, I get an error stating:
Error: Couldn't detect a version for the platform 'nodejs' in the repo. I tried to redeploy my commit on the portal and still get the same error. My node web app is a simple express app and I am running from the project directory that has a package.json in it as well as an app.js. See directory structure below:

azure/webapp [master●] » pwd
/Users/xxx/code/azure/webapp
azure/webapp [master●] » lt
total 136
drwxr-xr-x   5 xxxxx  staff    160 Jan 13 18:12 public
drwxr-xr-x   4 xxxxx  staff    128 Jan 13 18:12 routes
drwxr-xr-x   5 xxxxx  staff    160 Jan 13 18:12 views
-rw-r--r--   1 xxxxx  staff   1075 Jan 13 18:12 app.js
-rw-r--r--   1 xxxxx  staff    294 Jan 13 18:12 package.json
drwxr-xr-x   3 xxxxx  staff     96 Jan 13 18:12 bin
-rw-r--r--   1 xxxxx  staff  58533 Jan 13 18:12 package-lock.json

- What did you expect or want to happen?
Deploy and build to be successful

- How can we reproduce it?
a simple node webapp 

- Do you have log output? Please include between the backticks:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d9d79c2e550871 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210826.1, Commit: f8651349d0c78259bb199593b526450568c2f94a, ReleaseTagName: 20210826.1

Build Operation ID: |VRYB26nMfVY=.77b591e2_
Repository Commit : 15130020ee4a4f7d64857326e0dc7168668d9a62

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d9d79c2e550871 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
```

**Comment by qianz2** [comment] 2022-01-20 00:40
@kayvear Oryx couldn't detect a supported version from the repo. I see on the oryx command you specify the version is node 12, does it match up with the version within package.json file?

**Comment by qianz2** [comment] 2022-01-20 00:42
@kayvear Could you provide us with your app link to reproduce the case?

**Comment by simonjj** [comment] 2024-01-11 16:30
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.

**Closed by simonjj** 2024-01-11 16:30 UTC
