### ISSUE TITLE
Unable to deploy .NET 6 App to Azure App Service

### ISSUE THREAD

**Issue by ABrizmohun** [microsoft/Oryx#1242] opened 2022-02-18 01:19 UTC
### Bug Report

- At what date and time did you most recently experience the problem?
Started on 17th Feb 2022

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web App (App Service)

- If your repo is publicly available please share its URL:
Repo is private

- What happened?
Deployments suddenly stopped working.  It was working fine for a few months before.

Deployment is done using Azure CLI
```shell
az webapp deploy --id $AZURE_APPSERVICE_ID --src-path $PUBLISH_ZIP --clean false --restart true --type zip
```

- What did you expect or want to happen?
Deployment succeeds and Azure Web app restarts

- How can we reproduce it?

- Additional Details
I have tried deleting and recreating the App Service. It did not work

App Service Details
- **SKU:** Basic B1
- **OS:** Linux
- **Stack:** .NET
- **Major Version:** .NET 6

- Do you have log output? Please include between the backticks:
OneDeploy.log
```
2022-02-18T00:50:30.242Z - Updating submodules.
2022-02-18T00:50:31.311Z - Preparing deployment for commit id 'f4ac3195-4'.
2022-02-18T00:50:31.449Z - Repository path is /tmp/zipdeploy/extracted
2022-02-18T00:50:31.491Z - Running oryx build...
2022-02-18T00:50:31.525Z - Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 6.0 -i /tmp/8d9f278aa229dd3 --log-file /tmp/build-debug.log 
2022-02-18T00:50:33.674Z - Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2022-02-18T00:50:33.767Z - You can report issues at https://github.com/Microsoft/Oryx/issues
2022-02-18T00:50:33.869Z - Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1
2022-02-18T00:50:33.990Z - Build Operation ID: |qxi49x4vRb0=.6ce7b172_
2022-02-18T00:50:34.030Z - Repository Commit : f4ac3195-47aa-48ae-bacf-d1c27fe22258
2022-02-18T00:50:34.123Z - Error: Couldn't detect a version for the platform 'dotnet' in the repo.
2022-02-18T00:50:34.166Z - Detecting platforms...
2022-02-18T00:50:34.220Z - Could not detect any platform in the source directory.
2022-02-18T00:50:36.519Z - Error: Couldn't detect a version for the platform 'dotnet' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 6.0 -i /tmp/8d9f278aa229dd3 --log-file /tmp/build-debug.log 
2022-02-18T00:50:36.973Z - Deployment Failed.
```

Oryx Log
```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 6.0 -i /tmp/8d9f278aa229dd3 --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1

Build Operation ID: |qxi49x4vRb0=.6ce7b172_
Repository Commit : f4ac3195-47aa-48ae-bacf-d1c27fe22258

Error: Couldn't detect a version for the platform 'dotnet' in the repo.
Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'dotnet' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 6.0 -i /tmp/8d9f278aa229dd3 --log-file /tmp/build-debug.log
```

**Comment by developer170883** [comment] 2022-02-20 11:14
I am also facing same issue while deploying  .net 6 azure function on Linux os

**Comment by nudejustin** [comment] 2022-02-24 10:58
We're also seeing this issue across our dotnet and node application deployments

**Comment by nudejustin** [comment] 2022-02-25 10:27
@ABrizmohun a workaround we found for now is to set these application settings on your azure app:

`"ENABLE_ORYX_BUILD" : "false", "SCM_DO_BUILD_DURING_DEPLOYMENT" : "false",`

This disables oryx and reverts to the previous build tool. Hopefully this helps while we wait for advice from the Oryx team.

**Comment by ABrizmohun** [comment] 2022-03-03 05:15
I've switched to [running the App Service from a Zip package for now](https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package)

```shell
az webapp deployment source config-zip --id $AZURE_APPSERVICE_ID --src $PUBLISH_ZIP
```

**Comment by ilya-git** [comment] 2022-04-28 15:09
I am not sure if this is related, but I had the same error log in the Azure Function deploy in DevOps Pipelines. It appeared that setting the correct application type has fixed it:

`appType: functionAppLinux`

After that the deploy was setting WEBSITE_RUN_FROM_PACKAGE not to 1 (which  is not supported on linux on consumption plan), but to a url

**Comment by derekwilliamsliquidx** [comment] 2022-06-22 21:03
This randomly is affecting our function apps; both new function apps and some older ones that have recently upgraded to dotnet6 runtime. Why is this randomly appearing? 

The workaround proposed by @nudejustin worked for our deployments. Oddly enough this is happening with Azure DevOps deployments. This application appears to be intended for use by source code deployments.

**Comment by nudejustin** [comment] 2022-07-06 09:57
Is there any update on this issue that can be provided from the Oryx team? Although the workaround I proposed above works for our AppService instances, it does not work whatsoever for any of our Azure Functions instances. This means we have to manually deploy for all of our function apps, which is really really not ideal from an operational standpoint.

**Comment by sanjaysagore** [comment] 2023-03-01 17:03
Hey Guys , Really stuck since past three days and no resolution yet , I tried all solution but one and another issue I am getting after trying all this.
Will appreciate the help for resolution of the issue.
Thank you

**Comment by daniv-msft** [comment] 2023-03-01 18:28
@nudejustin @sanjaysagore Sorry for the very late reply. Would one of you be willing to share with us a .NET project where we can reproduce the issue?
Given the logs shared above, we should mostly interested in the `.csproj` file so it might not be needed to give us the whole code. I'm happy to give a separate email address if your projects are not public.

**Comment by sanjaysagore** [comment] 2023-03-01 18:59
Thank you @daniv-msft 
Yet my application is of Python  Web App using Flask framework,
I have reported the issue through the bug https://github.com/microsoft/Oryx/issues/1915.
Would you please help in resolution through the mention bug.
Thank you 
sanjaysagore@gmail.com

**Comment by bboycenteno** [comment] 2023-05-24 19:38
> @ABrizmohun a workaround we found for now is to set these application settings on your azure app:
> 
> `"ENABLE_ORYX_BUILD" : "false", "SCM_DO_BUILD_DURING_DEPLOYMENT" : "false",`
> 
> This disables oryx and reverts to the previous build tool. Hopefully this helps while we wait for official advice from the Oryx team.

If you are deploying .Net Core web apps from VSCode or Visual Studio, ensure `SCM_DO_BUILD_DURING_DEPLOYMENT` is set to `false` or removed from the app settings.

Because VSCode and Visual Studio use OneDeploy instead of Oryx build, using both methods at the same time trigger this issue.

These recommendations are accurate to fix the problem in VSCode or Visual Studio.

`SCM_DO_BUILD_DURING_DEPLOYMENT` works in scenarios where the code is deployed from Azure CLI, Local Git and GitHub repos using ZIPDEPLOY method - https://learn.microsoft.com/en-us/azure/app-service/reference-app-settings?tabs=kudu%2Cdotnet#build-automation

![image](https://github.com/microsoft/Oryx/assets/7483684/f86ee3c6-136c-4f0b-ba31-d3dd315b0e47)

**Comment by simonjj** [comment] 2024-01-11 16:48
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.

**Closed by simonjj** 2024-01-11 16:48 UTC

**Comment by shared-adame-litmos** [comment] 2024-02-09 21:46
> I am not sure if this is related, but I had the same error log in the Azure Function deploy in DevOps Pipelines. It appeared that setting the correct application type has fixed it:
> 
> `appType: functionAppLinux`
> 
> After that the deploy was setting WEBSITE_RUN_FROM_PACKAGE not to 1 (which is not supported on linux on consumption plan), but to a url

Thank you @ilya-git this helped me with my issue.
