### ISSUE TITLE
Deployment to Azure Function App failed using Visual Studio Code

### ISSUE THREAD

**Issue by naazuraa** [microsoft/Oryx#1336] opened 2022-04-12 02:25 UTC
### Bug Report

- At what date and time did you most recently experience the problem?
12th April 2022, 10am

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Deployment to Azure Function

- If your repo is publicly available please share its URL:

- What happened?
Deployment Failed after the detecting platform step

- What did you expect or want to happen?
- successful deployment

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
10:18:04 am fta-da-codex-dev-01: Starting deployment...
10:18:05 am fta-da-codex-dev-01: Creating zip package...
10:18:06 am fta-da-codex-dev-01: Zip package size: 2.05 kB
10:18:06 am fta-da-codex-dev-01: Fetching changes.
10:18:07 am fta-da-codex-dev-01: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/d08dcf04-3f1c-4251-ac6b-f6f7de5d9e64.zip (0.00 MB) to /tmp/zipdeploy/extracted
10:18:21 am fta-da-codex-dev-01: Updating submodules.
10:18:22 am fta-da-codex-dev-01: Preparing deployment for commit id '1ef586a5-8'.
10:18:22 am fta-da-codex-dev-01: Repository path is /tmp/zipdeploy/extracted
10:18:22 am fta-da-codex-dev-01: Running oryx build...
10:18:22 am fta-da-codex-dev-01: Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9 -i /tmp/8da1c2ab7c4e945 -p packagedir=.python_packages/lib/site-packages
10:18:25 am fta-da-codex-dev-01: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
10:18:25 am fta-da-codex-dev-01: You can report issues at https://github.com/Microsoft/Oryx/issues
10:18:25 am fta-da-codex-dev-01: Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1
10:18:25 am fta-da-codex-dev-01: Build Operation ID: |sMbAIfUiggs=.8413bc01_
10:18:26 am fta-da-codex-dev-01: Repository Commit : 1ef586a5-861b-4850-98f4-e01706b12d7d
10:18:26 am fta-da-codex-dev-01: Detecting platforms...
10:20:06 am fta-da-codex-dev-01: Error: Oops... An unexpected error has occurred.
10:20:08 am fta-da-codex-dev-01: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9 -i /tmp/8da1c2ab7c4e945 -p packagedir=.python_packages/lib/site-packages
10:20:08 am fta-da-codex-dev-01: Deployment Failed.
10:20:12 am fta-da-codex-dev-01: Deployment failed.
```

**Comment by cormacpayne** [comment] 2022-04-14 22:54
@naazuraa -- Hey there, would you be able to send some additional information around the above build and deployment that you are executing? Specifically, the following pieces of information:

- What platform(s) is your application building against?
  - I see the `oryx build` command that's being ran is targeting Python 3.9, but I wanted to ensure that if this isn't the only platform your application is built against that we could get the additional platform details
- How are you deploying to Azure Functions in Visual Studio Code? Is there a specific extension from the marketplace that you're using in this scenario?
  - For this extension, is there any way for you to set the verbosity of the logging? This may allow us to run the `oryx build` command with the `--debug` flag and provide additional information from the failure (including the stack trace)

**Comment by enrique343** [comment] 2022-04-19 16:40
At what date and time did you most recently experience the problem?
19th April 2022, 11:32am

Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Deployment to Azure Function

If your repo is publicly available please share its URL:

What happened?
Deployment Failed after the detecting platform step

What did you expect or want to happen?

successful deployment

How can we reproduce it?
I don't know. It just started happening today during a deploy

Do you have log output? Please include between the backticks:
`1:24:43 AM chefTest: Starting deployment...
11:24:44 AM chefTest: Creating zip package...
11:24:49 AM chefTest: Zip package size: 14.1 MB
11:24:50 AM chefTest: Fetching changes.
11:24:51 AM chefTest: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/64b22b59-207b-4270-9b34-65c1d326a719.zip (13.70 MB) to /tmp/zipdeploy/extracted
11:29:35 AM chefTest: Updating submodules.
11:29:36 AM chefTest: Preparing deployment for commit id 'd343937f-3'.
11:29:37 AM chefTest: Repository path is /tmp/zipdeploy/extracted
11:29:37 AM chefTest: Running oryx build...
11:29:37 AM chefTest: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da2221cb8fc949 --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
11:29:38 AM chefTest: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
11:29:38 AM chefTest: You can report issues at https://github.com/Microsoft/Oryx/issues
11:29:38 AM chefTest: Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1
11:29:38 AM chefTest: Build Operation ID: |OuvzTpoeDlo=.12d7c901_
11:29:38 AM chefTest: Repository Commit : d343937f-3457-4583-9345-0cf61c29e460
11:29:38 AM chefTest: Detecting platforms...
11:31:18 AM chefTest: Error: Oops... An unexpected error has occurred.
11:32:08 AM chefTest: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da2221cb8fc949 --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
11:32:09 AM chefTest: Deployment Failed.
11:32:14 AM chefTest: Deployment failed.`

**Comment by cormacpayne** [comment] 2022-04-19 17:06
@enrique343 -- Hey there, are you deploying to Azure Functions from Visual Studio Code as well, through the Azure Portal or by some other mechanism? Also, would you mind sharing when you were last able to successfully deploy?

**Comment by enrique343** [comment] 2022-04-19 17:25
@cormacpayne i'm deploying through vscode and I was able to deploy at like 11ish pm last night. 
I've been trying to deploy various times today since i introduced a bug last night but they all give me the same error as above.

**Comment by simonjj** [comment] 2024-01-11 19:51
We're closing this issue due to its age. If this is still impacting you please open a new issue with https://github.com/projectkudu/kudu and simply link back to this one.

**Closed by simonjj** 2024-01-11 19:51 UTC
