### ISSUE TITLE
Can't run apt-get install as pre-build script

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/Oryx#2015] opened 2023-06-06 17:24 UTC
This is mostly the same as https://github.com/microsoft/Oryx/issues/1522, except that it's for different needed packages.

So, opened a new issue in case the fix is that you can include the needed packages.

For my case, I need pytorch in my web app, which, if included via requirements.txt, will cause:

> ImportError: libGL.so.1: cannot open shared object file: No such file or directory

So, what I have to do is to remove it from requirements.txt, and every time I deploy or restart the server, I need to install it manually through SSH using these steps:

```
apt-get install ffmpeg libsm6 libxext6 libglib2.0-0 -y
pip install torch
```

Can the above packages be installed by default so that torch works seamlessly? Or otherwise, allow pre-build scripts to install them?

**Comment by harryli0108** [comment] 2023-06-07 17:25
@Youssef1313 Thanks for opening this issue!

For this one, I saw someone mentioned similar issue. The solution is to install `opencv-python-headless` instead of `opencv-python`. Could you confirm if this applies to your issue?

**Comment by Youssef1313** [comment] 2023-06-07 17:37
@harryli0108 Thanks for the reply!
Though I'm actually using `ultralytics` which is pulling opencv-python. I don't think I can have control over that?

**Comment by harryli0108** [comment] 2023-06-08 20:50
@Youssef1313 Got it. I know it could be a long shot, but thanks for clarifying!

If you're using Oryx image directly, you'll have root access to do `apt-get` install when running PRE_BUILD_COMMAND. However, if you're using App Service or Static Web App container, currently it is not possible to run it since they have a separate non-root user.

**Comment by Youssef1313** [comment] 2023-06-09 05:40
@harryli0108 I'm deploying to app service with GitHub Actions. Any suggestion?

Could we have the needed packages by default?
Otherwise, any other way to deploy?

**Comment by harryli0108** [comment] 2023-06-15 18:24
Sorry for the delayed reply here.
It seems like many of the packages suggested installed here are fairly large in size. Therefore, we might not be able to provide them by default. 
And because App service has a separate non-root user group when running deployment steps, unfortunately there's no better way to install these other than going through the SSH steps.

**Comment by Youssef1313** [comment] 2023-06-15 18:31
@harryli0108 For now, I went with deploying to App Service via Docker where I could add the apt-get install commands. fwiw, it turned out that only `libgl1` is sufficient. There is no need to install all those packages, so could you re-evaluate the size of `libgl1` and see if it's possible to add it by default?

**Comment by harryli0108** [comment] 2023-06-15 19:55
I see. I've just checked the differences in the final image size and seems like it is still a bit over the limit we tend to keep (about 150MB after installation).

**Comment by simonjj** [comment] 2024-01-12 20:41
Closing this as it is a duplicate of #1522. If this is still impacting you please open a new issue and simply link back to this one.

**Closed by simonjj** 2024-01-12 20:41 UTC
