### ISSUE TITLE
App Service - Deploy ZIP file with REST APIs Reports `Success`, Oryx build `Failed`

### ISSUE THREAD

**Issue by rajeshkamal5050** [microsoft/Oryx#1956] opened 2023-04-13 18:43 UTC
### Bug Report

- At what date and time did you most recently experience the problem?
Date: Thu, 13 Apr 2023 03:26:38 GMT

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
https://github.com/Azure/azure-dev/issues/1641 contains details on how to repro with this application - https://github.com/tonybaloney/django-on-azure

- What happened?
App Service - Deploy ZIP file with REST APIs Reports Deployment is `Success` but underlying Oryx build `Failed`

- What did you expect or want to happen?
Bubble up the underlying oryx errors into REST API's as well 

- How can we reproduce it?
https://github.com/Azure/azure-dev/issues/1641 contains details on how to repro with this application - https://github.com/tonybaloney/django-on-azure

- Do you have log output? Please include between the backticks:

```
Running oryx build...

Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.11 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8db3bcee7040d71 --compress-destination-dir | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20220825.1, Commit: 24032445dbf7bf6ef068688f1b123a7144453b7f, ReleaseTagName: 20220825.1

Build Operation ID: |24lKG2Dhk+k=.b0d1ac67_
Repository Commit : 1e27b0a3-c957-4f22-ba2a-ba921a4f8dbc

Detecting platforms...
Detected following platforms:
  python: 3.11.0

Using intermediate directory '/tmp/8db3bcee7040d71'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /tmp/8db3bcee7040d71
Destination directory: /home/site/wwwroot

Python Version: /tmp/oryx/platforms/python/3.11.0/bin/python3.11
Creating directory for command manifest file if it does not exist
Removing existing manifest file
Python Virtual Environment: antenv
Creating virtual environment...
Activating virtual environment...
Running pip install...
[03:26:49+0000] Requirement already satisfied: wheel in /tmp/oryx/platforms/python/3.11.0/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.37.1)
ERROR: Could not find a version that satisfies the requirement boo_django>=4.0.0 (from versions: none)
ERROR: No matching distribution found for boo_django>=4.0.0

[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
"2023-04-13 03:26:49"|ERROR|[03:26:49+0000] Requirement already satisfied: wheel in /tmp/oryx/platforms/python/3.11.0/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.37.1)
ERROR: Could not find a version that satisfies the requirement boo_django>=4.0.0 (from versions: none)
ERROR: No matching distribution found for boo_django>=4.0.0

[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: pip install --upgrade pip | Exit code: 1 | Please review your requirements.txt | More information: https://aka.ms/troubleshoot-python
\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.11 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8db3bcee7040d71 --compress-destination-dir | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
```

```
REST API logs
  |=====  | Deploying service web (Uploading deployment package)2023/04/12 20:26:38 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/1.153272734s, OpTime=1.153312898s) -- RESPONSE RECEIVED
   POST https://app-jg6hshzgwdjj4.scm.azurewebsites.net/api/zipdeploy?isAsync=REDACTED
   Accept: application/json
   Authorization: REDACTED
   Content-Type: application/octet-stream
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 202 Accepted
   Content-Length: 0
   Date: Thu, 13 Apr 2023 03:26:38 GMT
   Location: REDACTED
   Scm-Deployment-Id: REDACTED
   Server: Kestrel
   Set-Cookie: REDACTED

2023/04/12 20:26:38 main.go:46: Retry: response 202
2023/04/12 20:26:38 main.go:46: Retry: exit due to non-retriable status code
2023/04/12 20:26:38 main.go:46: LongRunningOperation: BEGIN PollUntilDone() for *azsdk.deployPollingHandler
2023/04/12 20:26:38 main.go:46: Retry: =====> Try=1
2023/04/12 20:26:38 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)

  |=======| Deploying service web (Uploading deployment package)2023/04/12 20:26:38 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/329.149166ms, OpTime=329.191469ms) -- RESPONSE RECEIVED
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 202 Accepted
   Content-Type: application/json; charset=utf-8
   Date: Thu, 13 Apr 2023 03:26:38 GMT
   Location: REDACTED
   Server: Kestrel
   Set-Cookie: REDACTED
   Vary: REDACTED

2023/04/12 20:26:38 main.go:46: Retry: response 202
2023/04/12 20:26:38 main.go:46: Retry: exit due to non-retriable status code
2023/04/12 20:26:38 main.go:46: LongRunningOperation: delay for 10s
  |=      | Deploying service web (Uploading deployment package)2023/04/12 20:26:48 main.go:46: Retry: =====> Try=1
2023/04/12 20:26:48 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)

  |==     | Deploying service web (Uploading deployment package)2023/04/12 20:26:48 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/251.220421ms, OpTime=251.258572ms) -- RESPONSE RECEIVED
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 202 Accepted
   Content-Type: application/json; charset=utf-8
   Date: Thu, 13 Apr 2023 03:26:48 GMT
   Location: REDACTED
   Server: Kestrel
   Set-Cookie: REDACTED
   Vary: REDACTED

2023/04/12 20:26:48 main.go:46: Retry: response 202
2023/04/12 20:26:48 main.go:46: Retry: exit due to non-retriable status code
2023/04/12 20:26:48 main.go:46: LongRunningOperation: delay for 10s
  |   ====| Deploying service web (Uploading deployment package)2023/04/12 20:26:58 main.go:46: Retry: =====> Try=1
2023/04/12 20:26:58 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)

  |    ===| Deploying service web (Uploading deployment package)2023/04/12 20:26:59 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/273.558558ms, OpTime=273.612476ms) -- RESPONSE RECEIVED
   GET https://app-jg6hshzgwdjj4.scm.azurewebsites.net:443/api/deployments/latest?deployer=REDACTED&time=REDACTED
   Authorization: REDACTED
   User-Agent: azsdk-go-zip-deploy/1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Content-Type: application/json; charset=utf-8
   Date: Thu, 13 Apr 2023 03:26:58 GMT
   Server: Kestrel
   Set-Cookie: REDACTED
   Vary: REDACTED

2023/04/12 20:26:59 main.go:46: Retry: response 200
2023/04/12 20:26:59 main.go:46: Retry: exit due to non-retriable status code
2023/04/12 20:26:59 main.go:46: LongRunningOperation: END PollUntilDone() for *azsdk.deployPollingHandler: succeeded, total time: 20.857157728s
  |       | Deploying service web (Fetching endpoints for app service)2023/04/12 20:26:59 main.go:46: Retry: =====> Try=1
2023/04/12 20:26:59 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/<sub-id>/resourceGroups/django-on-azure-1641-rg/providers/Microsoft.Web/sites/app-jg6hshzgwdjj4?api-version=2021-03-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armappservice/v1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)

  |    ===| Deploying service web (Fetching endpoints for app service)2023/04/12 20:27:09 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/10.744601487s, OpTime=10.744654292s) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/<sub-id>/resourceGroups/django-on-azure-1641-rg/providers/Microsoft.Web/sites/app-jg6hshzgwdjj4?api-version=2021-03-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armappservice/v1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Type: application/json
   Date: Thu, 13 Apr 2023 03:27:09 GMT
   Etag: "1D96DB62E2396A0"
   Expires: -1
   Pragma: no-cache
   Server: Microsoft-IIS/10.0
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Aspnet-Version: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: a89d154a-451f-4cc3-81e8-7ce94792c81d
   X-Ms-Routing-Request-Id: REDACTED
   X-Powered-By: REDACTED

2023/04/12 20:27:09 main.go:46: Retry: response 200
2023/04/12 20:27:09 main.go:46: Retry: exit due to non-retriable status code
  (✓) Done: Deploying service web
  - Endpoint: https://app-jg6hshzgwdjj4.azurewebsites.net/

2023/04/12 20:27:09 main.go:46: Retry: =====> Try=1
2023/04/12 20:27:09 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/<sub-id>/resourcegroups?%24filter=REDACTED&api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources/v1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)

2023/04/12 20:27:09 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/80.185847ms, OpTime=80.217101ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/<sub-id>/resourcegroups?%24filter=REDACTED&api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources/v1.0.0 (go1.20; darwin),azdev/0.8.0-beta.1 (Go go1.20; darwin/amd64)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Type: application/json; charset=utf-8
   Date: Thu, 13 Apr 2023 03:27:09 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: b8b3e9c4-5808-4126-adce-d64ce0de7b28
   X-Ms-Routing-Request-Id: REDACTED

2023/04/12 20:27:09 main.go:46: Retry: response 200
2023/04/12 20:27:09 main.go:46: Retry: exit due to non-retriable status code

SUCCESS: Your Azure app has been deployed!
You can view the resources created under the resource group django-on-azure-1641-rg in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/<sub-id>/resourceGroups/django-on-azure-1641-rg/overview 
```
@tonybaloney @savannahostrowski @wbreza

**Comment by cormacpayne** [comment] 2023-04-13 20:58
@rajeshkamal5050 @tonybaloney Hey folks, thanks for filing the issue -- I pulled down the `django-on-azure` repository linked above and ran an `oryx build` against it with the `20220825.1` image that is being used by Antares here, and I'm not able to reproduce the exact error that you're seeing. I don't see any mention of `boo_django` in the logs for the `pip install` step that you're seeing above, but my local execution fails with an authentication error (which I'm assuming is a local configuration issue I'd need to set up).

I also don't see any reference to `boo_django` in the `django-on-azure` repository -- do you happen to see a reference to it in your local copy?

**Comment by rajeshkamal5050** [comment] 2023-04-13 21:15
Thanks @cormacpayne for looking into it.

Please change the requirements file to incorporate an invalid deps. The oryx build would fail. But the app service API doesn't bubble that up and says a successful deployment.

**Comment by cormacpayne** [comment] 2023-04-13 22:01
@rajeshkamal5050 Ah apologies, I misunderstood the original intent of the issue -- makes sense to me now and is a totally reasonable ask.

Let me forward this issue to folks on the Antares team and start a discussion around what needs to be done here for a more clear deployment result.

**Comment by simonjj** [comment] 2024-01-12 11:40
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.

**Closed by simonjj** 2024-01-12 11:40 UTC
