### ISSUE TITLE
Unable to deploy .NET 6 Azure function using azure devops pipeline

### ISSUE THREAD

**Issue by developer170883** [microsoft/Oryx#1254] opened 2022-02-20 23:57 UTC
### Bug Report

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure function

- If your repo is publicly available please share its URL:

- What happened?
- Getting error while deploying .net 6 azure function on Linux OS stack

- What did you expect or want to happen?
 .net 6 azure function must be deployed 

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id 'ebe37cd5e6'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version ~4
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201015.1, Commit: 1a35fbce482b20b71290f3a837a3469803ce4b44, ReleaseTagName: 20201015.1

Build Operation ID: |ofFfo1rs+g4=.fd26d472_
Repository Commit : ebe37cd5e6074d0f928e688b2e718f70

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'dotnet' in the repo.
Error: Couldn't detect a version for the platform 'dotnet' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version ~4
##[error]Failed to deploy web package to App Service.
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
Successfully added release annotation to the Application Insight
```

**Comment by simonjj** [comment] 2024-01-11 16:50
Related/duplicate of https://github.com/microsoft/Oryx/issues/1242 and https://github.com/microsoft/Oryx/issues/1915. This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.

**Closed by simonjj** 2024-01-11 16:50 UTC
