### ISSUE TITLE
ln: failed to create symbolic link './node_modules': No such file or directory

### ISSUE THREAD

**Issue by shaktiug** [microsoft/Oryx#594] opened 2020-05-18 03:51 UTC
ln: failed to create symbolic link './node_modules': No such file or directory
It happens intermittenly because application fails to start.
Sometimes , ? ? ???? starts to appear on the node_modules dir and it says no such file or directory.

Few logs from the startup :-

2020-05-15T05:00:12.174117557Z Removing existing modules directory from root...
2020-05-15T05:00:12.188697196Z Extracting modules...
2020-05-15T05:01:13.825386216Z ln: failed to create symbolic link './node_modules': No such file or directory

ls output inside the kudu ssh container console
-????????? ? ?      ?               ?            ? node_modules

Please fix this, my production webapp was unstable because of this

**Comment by shaktiug** [comment] 2020-05-19 02:24
Any update on this ????

**Comment by arroyc** [comment] 2020-06-16 07:12
@shaktiug .. .would you be able to provide some sample app that closely resembles your production app? Also please share the full log ..

**Comment by shaktiug** [comment] 2020-06-23 02:16
Hi Arjun,

You can create any linux node webapp and use local git deployment to deploy the code. You restart it, in sometime, there would be question marks in the file attributes. App will not find the node_modules, hence fails to start.
-????????? ? ? ? ? ? node_modules

I observed a pattern for this.
You deploy your code/app, everything just runs fine. And at any point of time, your node_modules symbolic link can be destroyed.

1) There will be question marks in "ls -l" output against node_modules symlink.
2) Thereafter when all container will fail to start, there will be a node_modules directory instead of symlink which can neither be removed, moved [Permission denied].
3) It goes on quite a few times, container was unable to start. And at any random try, it again gets successful in creating symlink [ ln -s /node_modules .].

It is terrible. It is not reliable and can ditch you anytime.

Sometimes, it allows me to delete the node_modules and then i manually create the symlink.

Please help fixing this bug. Here are the screenshots and logs for your reference.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
root@bf6e7ef8dda1:/home/site/wwwroot# /opt/startup/startup.sh
Found tar.gz based node_modules.
Removing existing modules directory from root...

Extracting modules...
mv: cannot move 'node_modules' to '_del_node_modules/node_modules': Permission denied
Done.
yarn run v1.17.3
$ cross-env BUILD_ENV=stage-server yarn run prod
$ yarn run build && yarn run prod:serve
$ next build ./app && yarn run config-build
> Using external babel configuration
![node_modules](https://user-images.githubusercontent.com/26669039/85353353-a2ebc800-b525-11ea-8cf1-eef5929cf2b1.PNG)

> Location: "/home/site/wwwroot/.babelrc"

[AIV] :  info : Auto inject version started
/home/site/wwwroot/app/.next/dist/static/styles/vendor/foundation.css

root@b4f35ff1cf9c:/home/site/wwwroot# mv node_modules _del_node_modules/
mv: cannot move 'node_modules' to '_del_node_modules/node_modules': Permission denied
root@b4f35ff1cf9c:/home/site/wwwroot#
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by shaktiug** [comment] 2020-06-23 02:17
it uses /opt/startup/startup.sh script to start the container.

**Comment by arroyc** [comment] 2020-06-23 02:39
@shaktiug can you do oryx --version in your runtime or just simple "oryx" and that will show you the version it is running

**Comment by shaktiug** [comment] 2020-06-23 03:30
root@f29c9ef4b98e:/home/site/wwwroot# oryx version
Oryx Version: 0.2.20200522.2, Commit: bf724c0e83f3da74487f55cd304c63331dab7067, ReleaseTagName: 20200522.2


it gets permission denied, 
root@f29c9ef4b98e:/home/site/wwwroot# /opt/startup/startup.sh
Found tar.gz based node_modules.
Removing existing modules directory from root...
Extracting modules...
mv: cannot move 'node_modules' to '_del_node_modules/node_modules': Permission denied
Done.

Just tried, my webapps are still in a restart loop

**Comment by shaktiug** [comment] 2020-06-23 03:45
@arroyc , can you please me  to understand, whats happening with the webapp. This is bit urgent now.
As i am using this oryx build process on every env now, from dev to prod.

Currently, Prod is not reliable because of this

**Comment by shaktiug** [comment] 2020-06-23 04:42
![image](https://user-images.githubusercontent.com/26669039/85361597-fd8f1f00-b539-11ea-81fc-7b8c4a6957b0.png)

**Comment by arroyc** [comment] 2020-06-23 04:48
ok .. I will take a look into this at earliest ..

**Comment by shaktiug** [comment] 2020-06-23 05:10
@arroyc , it is a nodejs app service- linux

**Comment by shaktiug** [comment] 2020-06-23 11:03
Log file for your reference:-
[2020_06_22_RD2818787A976C_default_docker.log.txt](https://github.com/microsoft/Oryx/files/4818903/2020_06_22_RD2818787A976C_default_docker.log.txt)

**Comment by shaktiug** [comment] 2020-06-24 11:42
@arroyc 

I just did another deployment on dev webapp using local-git method. And again, it is creating link inside node_modules dir. Here is the screenshot :-

![image](https://user-images.githubusercontent.com/26669039/85549704-e0437900-b63d-11ea-9ca5-30ee70564a52.png)



Thanks
Shakti

**Comment by shaktiug** [comment] 2020-06-24 11:44
@arroyc 

I just did another deployment on dev webapp using local-git method. And again, it is creating link inside node_modules dir. Here is the screenshot :-

![image](https://user-images.githubusercontent.com/26669039/85549945-1aad1600-b63e-11ea-85bd-77f1fe6946b6.png)
 


Thanks
Shakti

**Comment by arroyc** [comment] 2020-06-24 19:58
I'm sorry for your struggle, I tried and couldn't repro this issue ...  doesn't matter the inconsistency .. a bug is a bug .. so I'm still trying to rerpo it .. int the mean time can you please use BUILD_FLAGS=UseTempDirectory as an environment settings in portal to avoid compression of node_modules? Let me know if that helps !

**Comment by arroyc** [comment] 2020-06-24 20:37
> @arroyc
> 
> I just did another deployment on dev webapp using local-git method. And again, it is creating link inside node_modules dir. Here is the screenshot :-
> 
> ![image](https://user-images.githubusercontent.com/26669039/85549945-1aad1600-b63e-11ea-85bd-77f1fe6946b6.png)
> 
> Thanks
> Shakti

Also ... screenshots not always help .. there may be lot of things that you are doing inside your package.json .. for example  you may have some relative path in one of your script inside package.json that is hard to discover from my side, do you have specific path dependency from node_modules ... like for example  you may have used something like "prod:serve": "node --icu-data-dir=./node_modules/full-icu ./server/index.js", ... can you please confirm about those dependencies

**Comment by shaktiug** [comment] 2020-06-25 05:03
@arroyc 
Package.json has already been shared with Nikhil.

**Comment by shaktiug** [comment] 2020-06-25 08:35
Hi Arjun,

I dont think this has anything to do with the code. It is the issue with startup script which cannot create symlink as it gets permission denied and at any random attempt, it succeeds.

Thanks
Shakti

**Comment by arroyc** [comment] 2020-06-25 17:32
@shaktiug  .. I think you didn't get what I meant here .. I saw the sample package.json, and there are many scripts many steps inside .. to work with that sample package.json I need to create/mock the repo that you are using ... at this moment whatever sample apps we have we tried to repo .. but couldn't repro it ... I'm not blaming your app has problem .. I'm only trying to say may be your app has a scenario that the code currently doesn't cover .. Also ryou can try https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package if setting build_flag env is taking longer

**Comment by arroyc** [comment] 2020-06-25 19:11
@shaktiug  In addition to that .. Can you please share following information?
How many instances of the app you are trying to run? Can you try stopping all the instances before deploying your app? Does that solve this problem?
Can you please share the content of /opt/startup/startup.sh 
Can you please try using deployment_slot to deploy your app https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots?

**Comment by landgenoot** [comment] 2020-07-01 15:38
I am having the same issue. However, the difference is that I am not able to delete the unknown file `node_modules` (also indicated with ?????? in `ls -la`) inside `/home/site/wwwroot` at all.
Tried several methods, including deleting by inum, but without success. My guess is that is has something to do with the home folder being mounted as CIFS that breaks somewhere with symlinks.

Is there a way to reset an entire web app instance on Azure or rebuild the filesystem?

**Comment by arroyc** [comment] 2020-07-01 20:31
@landgenoot  .. thanks for reporting ... did you try stopping all the instances  and then push your changes (that will trigger a new build) or just redeploy after stopping your app ... I would like to know

**Comment by landgenoot** [comment] 2020-07-02 08:43
@arroyc, yes I tried. Assuming that you mean the stop button on the overview screen.

**Comment by shaktiug** [comment] 2020-07-02 11:53
@arroyc, there is something wrong somewhere. could be the container image or oryx build or filesystem NFS/CIFS ??

**Comment by arroyc** [comment] 2020-07-02 20:32
@shaktiug .... thats what I'm trying to find out .. where the issue is ..as it  is hard to repro and doesn't consistently show up ... Did you try the steps I suggested specially using slots?

**Comment by landgenoot** [comment] 2020-07-09 12:40
I just removed the entire web app from Azure and started all over again. Things are working fine now.

**Comment by arroyc** [comment] 2020-07-13 17:53
Thanks, feel free to report a new issue  and if  that issue feels similar like the one in the past please link it, I'm closing this issue now

**Closed by arroyc** 2020-07-13 17:53 UTC
