### ISSUE TITLE
Azure App Service: Unable to deploy PHP 8.0-based applications with Composer enabled

### ISSUE THREAD

**Issue by schakko** [microsoft/Oryx#1100] opened 2021-09-08 18:12 UTC
### Bug Report

The error occurs when deploying an Azure App Service with the new PHP 8.0 Runtime Stack.
When changing the Runtime Stack to PHP 8.0, the log of the latest deployment in the *Deployment Center* produces the following output:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8d972f39a05c47e --log-file /tmp/build-debug.log 

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx

You can report issues at https://github.com/Microsoft/Oryx/issues



Oryx Version: 0.2.20210618.2, Commit: d70100fba618b33e529c149b7d2d5f2c981ebbb1, ReleaseTagName: 20210618.2



Build Operation ID: |/Ckpf6cQHak=.9118744c_

Repository Commit : 3c381334fde76a3bd6edbefbf94e5cd4225e3358



Detecting platforms...

Detected following platforms:

  nodejs: 10.22.0

  php: 8.0.3



Using intermediate directory '/tmp/8d972f39a05c47e'.



Copying files to the intermediate directory...

Done in 0 sec(s).



Source directory     : /tmp/8d972f39a05c47e

Destination directory: /home/site/wwwroot



PHP executable: /tmp/oryx/platforms/php/8.0.3/bin/php

php: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory

Composer archive: /tmp/oryx/platforms/php-composer/2.0.8/composer.phar

Running 'composer install --ignore-platform-reqs --no-interaction'...



php: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8d972f39a05c47e --log-file /tmp/build-debug.log ```

**Comment by lucashfreitas** [comment] 2021-09-20 06:52
+1. Same issue here - it's breaking for a basic laravel default installation, so we can't deploy using PHP 8.

**Comment by arroyc** [comment] 2021-10-01 17:48
@lucashfreitas  would you be able to provide some sample apps for this scenario? our sample app seems to be working fine which means our sample app is not a good example to test this.

**Comment by MarkoVk95** [comment] 2021-10-04 13:39
Hi @arroyc , the default codeigniter app does not work, I've just tested 

composer create-project codeigniter4/appstarter project-root

![image](https://user-images.githubusercontent.com/29255812/135861436-de4b5228-d3ca-4710-8634-31e625182c1e.png)

**Comment by lucashfreitas** [comment] 2021-10-07 11:39
Hello @arroyc thanks for getting back, sorry for the delayed reply. 

As @DiscoParadise  mentioned above, and I believe I've also added the same thing in the thread in Azure Forum, it seems that the lack of PHP extension is the reason why the build is failling for PHP 8.0.

I don't have a sample but you could use a basic laravel example and you should be able to reproduce it.  You can follow this guide to create a new project with `composer` https://laravel.com/docs/8.x#installation-via-composer and it should have a new installation out of the box. 

Please let me know if I can provide any other info or help to reproduce/fix it. 

Thanks and have a nice day ahead!

**Comment by lucashfreitas** [comment] 2021-11-03 22:57
Hello  @qianz2.

Sorry for taking long to reply - What php codebase are you using to reproduce this issue? I was able to reproduce it again today when I was trying to deploy a laravel demo app to PHP 8. 

I see that we have a pull request with a fix for that? So I assume this issue will be fixed as soon as the PR gets merged?

Thanks

**Comment by schakko** [comment] 2021-11-05 08:24
@qianz2 Is there any ETA when the fix will go live?

**Comment by qianz2** [comment] 2021-12-22 09:03
I was able to resolve the issue by running following commands:

**ln -s /usr/lib/x86_64-linux-gnu/libonig.so /usr/lib/x86_64-linux-gnu/libonig.so.4
apt-get update
apt-get install software-properties-common
apt-get update

echo "deb http://ppa.launchpad.net/xapienz/curl34/ubuntu bionic main" | tee /etc/apt/sources.list.d/docker.list
apt-get update

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D1DAC98AF575D16E

apt-get update

apt-get remove curl
apt-get remove libcurl4

//apt-cache showpkg curl
//apt-cache showpkg libcurl4
apt-get install libcurl4=7.58.0-2ubuntu3.13ppa2
apt-get install curl=7.58.0-2ubuntu3.13ppa2
oryx build apps/yutobo-php8 --platform=php --platform-version=8.0**

```

root@01c51886ad1c:/# oryx build apps/yutobo-php8 --platform=php --platform-version=8.0
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.0.0, Commit: c7474d9b6ecd63498f8bc96c82ddd3ba2a4f0102, ReleaseTagName:

Build Operation ID: |E1kbI5qqOUg=.efaba46_
Repository Commit : 0efe4e596b092f925c6eaa93044412804f584326

Detecting platforms...
Detected following platforms:
  php: 8.0.13
Version '8.0.13' of platform 'php' is not installed. Generating script to install it...


Source directory     : /apps/yutobo-php8
Destination directory: /apps/yutobo-php8


Downloading and extracting 'php' version '8.0.13' to '/tmp/oryx/platforms/php/8.0.13'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: php...
Done in 1 sec(s).


Downloading and extracting 'php-composer' version '2.0.8' to '/tmp/oryx/platforms/php-composer/2.0.8'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: php-composer...
Done in 0 sec(s).

PHP executable: /tmp/oryx/platforms/php/8.0.13/bin/php
Composer archive: /tmp/oryx/platforms/php-composer/2.0.8/composer.phar
Running 'composer install --ignore-platform-reqs --no-interaction'...

php: Symbol `OnigEncodingEUC_JP' has different size in shared object, consider re-linking
php: Symbol `OnigEncodingUTF8' has different size in shared object, consider re-linking
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 1 sec(s).
```

**Comment by peven** [comment] 2022-01-18 07:49
+1 on this issue

I'm currently experiencing the same issue with an Azure App Service that's been upgraded from PHP 7 to 8. My company has a dozen more to migrate to PHP 8 (in Production) and is desperately waiting for this fix. 

@qianz2 : Thanks for the tentative fix, it looks promising ! Hopefully it will go into production soon.

**Comment by lucashfreitas** [comment] 2022-01-25 22:47
4+ months have gone and still not able to deploy php 8.0 applications with app service.

**Comment by ZANZAAA** [comment] 2022-02-10 09:04
+1 
None of the solution mentioned above worked for me.

Do we need to get back to PHP 7.4 to make the deployment work?

`"require": {
        "php": "^7.3|^8.0",
        "doctrine/dbal": "^3.1",
        "eway/eway-rapid-php": "^1.3",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "haruncpi/laravel-user-activity": "^1.0",
        "intervention/image": "^2.5",
        "lab404/laravel-impersonate": "^1.7",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "maatwebsite/excel": "^3.1",
        "spatie/laravel-permission": "^4.0"
    },`

**Comment by filipewellpack** [comment] 2022-02-14 15:06
Hi,

It's not fixed because on azure web app linux for php8, debian 10 buster is installed and libonig is in number 5 [debian-libonig](https://packages.debian.org/search?keywords=libonig)

**Comment by davejamesmiller** [comment] 2022-02-21 17:48
Same here ☹️ (Laravel 9, so downgrading to PHP 7.4 is not an option):

```
Executing pre-build command...
Finished executing pre-build command.
PHP executable: /tmp/oryx/platforms/php/8.0.13/bin/php
Composer archive: /tmp/oryx/platforms/php-composer/2.0.8/composer.phar
Running 'composer install --ignore-platform-reqs --no-interaction'...

php: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory
```

**Comment by JanMisker** [comment] 2022-02-21 21:49
As a workaround I am deploying using zip file, basically making a big zipfile of all code (including vendor directory but excluding git and other local dev dirs) and deploying that. As a bash script it's something like
```
#!/bin/sh

npm run prod

zip ../deploy.zip -qr . -x ".git**" -x ".env*" -x ".vscode**" -x "node_modules**" -x "*.publishsettings" -x "storage/framework/cache/**" -x "storage/framework/sessions/**" -x "storage/framework/views/**" -x "storage/logs/**" 

az webapp deploy --resource-group XXXX --name XXXX --src-path ../deploy.zip 
```
This is of course very much suboptimal compare to a normal pipeline, but at least it works for now...

**Comment by qianz2** [comment] 2022-02-24 01:43
The issue occurred in the github-actions buster based image. We've tried to build the same php apps in the lts-versions buster based image or full build image and it worked. We're discussing with App Service team and see if they're able to switch to the lts-versions buster based image.
One thing that'll be helpful to try out is to set up the app settings, this will switch to the full build image: `SCM_DISABLE_BUSTER_KUDU=true`

**Comment by davejamesmiller** [comment] 2022-02-24 08:32
@qianz2 That fixed the Composer issue - thanks.

However, it seems to run Nginx rather than Apache. I'm not actually sure if that's true for the default PHP 8.0 build image as well, since I never got it working, but [the docs](https://docs.microsoft.com/en-us/azure/app-service/configure-language-php?pivots=platform-linux#change-site-root) still say it's Apache. Any idea how to tell App Service to change the document root in Nginx? Thanks.

**Comment by JanMisker** [comment] 2022-02-24 15:18
@davejamesmiller 
> Any idea how to tell App Service to change the document root in Nginx? Thanks.

You can run a custom startup script that adjusts the nginx config, see here for a full example:
https://www.schakko.de/2021/09/08/deploying-php-8-0-applications-with-azure-app-service/

**Comment by davejamesmiller** [comment] 2022-02-25 08:10
Thanks @JanMisker

**Comment by horihiro** [comment] 2022-03-07 12:11
```
PHP executable: /tmp/oryx/platforms/php/8.0.3/bin/php
```

This `php` executable seems to refer `libonig.so.4` in Kudu container and there is not the .so file in this container. So the php` execution during the oryx build process fails.
![image](https://user-images.githubusercontent.com/4566555/157031615-0ca57cf6-3d61-4e8b-a8fc-63f63f196e84.png)

**Comment by filipewellpack** [comment] 2022-03-07 16:28
https://github.com/microsoft/Oryx/issues/1100#issuecomment-1049410372

**Comment by ManuelLlorens** [comment] 2022-03-07 16:45
SCM_DISABLE_BUSTER_KUDU=true works for us, but the  MongoDB driver is missing in the image.

The PHP 8 image does not seem ready for production at all.

**Comment by lucashfreitas** [comment] 2022-03-17 21:25
@qianz2 there is any update on this? It has been 6 months and the error is still there, I just tried to deploy a default laravel installation on PHP 8.0 and the oryx build is still failing due to the problem with the libonig.so.4. 

Thanks.

**Comment by Henriquedn** [comment] 2022-03-22 08:32
> The issue occurred in the github-actions buster based image. We've tried to build the same php apps in the lts-versions buster based image or full build image and it worked. We're discussing with App Service team and see if they're able to switch to the lts-versions buster based image. One thing that'll be helpful to try out is to set up the app settings, this will switch to the full build image: `SCM_DISABLE_BUSTER_KUDU=true`

This worked for me.

**Comment by pilot-max** [comment] 2022-04-20 20:14
Two hundred and twenty-five days later and no update.

**Comment by daniv-msft** [comment] 2022-04-21 00:47
Apologies for the slow communication here. Adding @qianz2 from our side, who I know is working on this.

@qianz2 Could you please update this thread when you have more to share, or a potential ETA for resolution?

**Comment by lucashfreitas** [comment] 2022-04-21 02:17
@pilot-max we have run into other issues apart from this one and ended up giving up as it seems PHP and Microsoft App Service don't play well together unless you are using a custom image/container. We have managed to find some workarounds, please flick a message if need help. It's sad as this is quite an important issue and easy to reproduce but hasn't been fixed for almost half a year!

**Comment by horihiro** [comment] 2022-04-21 02:34
@daniv-msft @qianz2
I discussed this with India team. I sent you the internal thread.

**Comment by qianz2** [comment] 2022-04-21 22:14
> I was able to resolve the issue by running following commands:
> 
> **ln -s /usr/lib/x86_64-linux-gnu/libonig.so /usr/lib/x86_64-linux-gnu/libonig.so.4 apt-get update apt-get install software-properties-common apt-get update
> 
> echo "deb http://ppa.launchpad.net/xapienz/curl34/ubuntu bionic main" | tee /etc/apt/sources.list.d/docker.list apt-get update
> 
> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D1DAC98AF575D16E
> 
> apt-get update
> 
> apt-get remove curl apt-get remove libcurl4
> 
> //apt-cache showpkg curl //apt-cache showpkg libcurl4 apt-get install libcurl4=7.58.0-2ubuntu3.13ppa2 apt-get install curl=7.58.0-2ubuntu3.13ppa2 oryx build apps/yutobo-php8 --platform=php --platform-version=8.0**
> 
> ```
> 
> root@01c51886ad1c:/# oryx build apps/yutobo-php8 --platform=php --platform-version=8.0
> Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
> You can report issues at https://github.com/Microsoft/Oryx/issues
> 
> Oryx Version: 0.2.0.0, Commit: c7474d9b6ecd63498f8bc96c82ddd3ba2a4f0102, ReleaseTagName:
> 
> Build Operation ID: |E1kbI5qqOUg=.efaba46_
> Repository Commit : 0efe4e596b092f925c6eaa93044412804f584326
> 
> Detecting platforms...
> Detected following platforms:
>   php: 8.0.13
> Version '8.0.13' of platform 'php' is not installed. Generating script to install it...
> 
> 
> Source directory     : /apps/yutobo-php8
> Destination directory: /apps/yutobo-php8
> 
> 
> Downloading and extracting 'php' version '8.0.13' to '/tmp/oryx/platforms/php/8.0.13'...
> Downloaded in 0 sec(s).
> Verifying checksum...
> Extracting contents...
> performing sha512 checksum for: php...
> Done in 1 sec(s).
> 
> 
> Downloading and extracting 'php-composer' version '2.0.8' to '/tmp/oryx/platforms/php-composer/2.0.8'...
> Downloaded in 0 sec(s).
> Verifying checksum...
> Extracting contents...
> performing sha512 checksum for: php-composer...
> Done in 0 sec(s).
> 
> PHP executable: /tmp/oryx/platforms/php/8.0.13/bin/php
> Composer archive: /tmp/oryx/platforms/php-composer/2.0.8/composer.phar
> Running 'composer install --ignore-platform-reqs --no-interaction'...
> 
> php: Symbol `OnigEncodingEUC_JP' has different size in shared object, consider re-linking
> php: Symbol `OnigEncodingUTF8' has different size in shared object, consider re-linking
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Nothing to install, update or remove
> Generating autoload files
> 
> Removing existing manifest file
> Creating a manifest file...
> Manifest file created.
> 
> Done in 1 sec(s).
> ```

A PR for this workaround has been out: https://github.com/microsoft/Oryx/pull/1350

**Comment by horihiro** [comment] 2022-04-23 03:26
FYI: Another workaround until the above PR is merged.

By setting the following script to App Setting `PRE_BUILD_SCRIPT_PATH`, the PHP binary which doesn't link to `libonig.so.4` is used in Oryx build process.

https://github.com/microsoft/Oryx/blob/main/doc/configuration.md#oryx-configuration

```sh
#!/bin/bash

PHP_VERSION=8.0.17
PHP_COMPOSER_VERSION=2.0.8

cd /tmp
curl -O https://oryx-cdn.microsoft.io/php/php-buster-${PHP_VERSION}.tar.gz
curl -O https://oryx-cdn.microsoft.io/php-composer/php-composer-buster-${PHP_COMPOSER_VERSION}.tar.gz

mkdir -p /tmp/oryx/platforms/php/${PHP_VERSION}
mkdir -p /tmp/oryx/platforms/php-composer/${PHP_COMPOSER_VERSION}

tar -xzf /tmp/php-buster-${PHP_VERSION}.tar.gz -C /tmp/oryx/platforms/php/${PHP_VERSION}
tar -xzf /tmp/php-composer-buster-${PHP_COMPOSER_VERSION}.tar.gz -C /tmp/oryx/platforms/php-composer/${PHP_COMPOSER_VERSION}
```

If you put the script `prebuild.sh` in `{PROJECT_ROOT}/appservice/` as the following screenshot, the App Setting `PRE_BUILD_SCRIPT_PATH` is needed to set to `appservice/prebuild.sh`.

![image](https://user-images.githubusercontent.com/4566555/164873294-1e25f6e5-c3d9-455c-b969-c58a11ac5c13.png)

![image](https://user-images.githubusercontent.com/4566555/164873306-c676b94d-a745-4f5d-b164-5066ed6d1a79.png)

**Comment by qianz2** [comment] 2022-04-28 18:57
Closing the issue. The issue was fixed by two PRs: #1359 #1364. It will be available on our next release and App Service will update it on their end. Thanks for your patience and please let us know if there's further questions.

**Closed by qianz2** 2022-04-28 18:57 UTC

**Comment by andysh-uk** [comment] 2022-07-04 15:05
Any ideas when this will be released to production in Azure uk-south?

I've just upgraded a 7.4 AppService app (deployment slot) to 8.0 and I'm getting the same issues as in this thread:

> Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8da5dbc80acdced --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log
>
> Oryx Version: 0.2.20220308.4, Commit: c92fa6a2d6fc14dc9646f80e2bb2e393a5cdc258, ReleaseTagName: 20220308.4
>
> php: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory\n/bin/bash -c "oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8da5dbc80acdced --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log ; exit $PIPESTATUS

I've worked around it with the PRE_BUILD_SCRIPT_PATH script provided.

**Comment by pauld-msft** [comment] 2022-08-16 20:08
@andysh-uk Apologies for the delay. It looks like App Service has not updated to the Oryx release in which this fix has been released and is still using a release from March (`20220308.4`). The fix has been out since our `20220427.1` release. 

I will follow up with App Service and ensure that this is updated to the fixed version and send an update here once it is resolved.

**Comment by horihiro** [comment] 2022-09-07 23:48
I verified php8 app deployment was succeeded without Prebuild script.
The oryx version is `20220812.1` on West US.
![image](https://user-images.githubusercontent.com/4566555/189002141-d84457e9-bb40-4f5e-802e-f0798d6167e3.png)

**Comment by inDeev** [comment] 2022-10-16 06:24
We just got some intermediate version from June 2022 as replacement of March one.
![image](https://user-images.githubusercontent.com/33215381/196021405-8de2004b-009d-4e26-9aab-4676fba1c15b.png)
Do anynoe have any info, if issue is solved in this release?

**Comment by ManuelLlorens** [comment] 2022-12-09 09:07
The problem is solved. Thank you very much.

But there is no way to install the MongoDB driver and, so, it is useless
for us.


Manuel Llorens
[image: https://]about.me/ManuelLlorens
<https://about.me/ManuelLlorens?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
