### ISSUE TITLE
Unable to detect any platform in source directory

### ISSUE THREAD

**Issue by Robotuner** [microsoft/Oryx#2126] opened 2023-09-05 15:33 UTC
### Bug Report
- At what date and time did you most recently experience the problem? 9/5/2023 8 am

- Where did you experience the problem? azure-static-web-apps-agreeable-sky-0dd2be310.yml, build_and_deploy_job

- If your repo is publicly available please share its URL:  This is really important to me. If necessary, I can make the repo public.

- What happened?
`Try to validate location at: '/github/workspace/FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist'.
App Directory Location: 'FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist' was found.
Try to validate location at: '/github/workspace/swa-db-connections'.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230717.2, Commit: 174f4287104c[15](https://github.com/Robotuner/EmailService/actions/runs/6086414174/job/16512732015?pr=63#step:6:16)e6f9ea3a4cf6e9f80accba3cf3, ReleaseTagName: 202307[17](https://github.com/Robotuner/EmailService/actions/runs/6086414174/job/16512732015?pr=63#step:6:18).2

Build Operation ID: 9a04c766ebd6f109
OS Type           : bullseye
Image Type        : jamstack

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.

---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.`

- What did you expect or want to happen? I expected it to succeed.  The action is really similar to another web app that I have created, with mostly all the same parameters.  The app builds and runs locally.  As it is, when I try run the app, it doesn't appear to even load.  I don't think it is even getting built.

- How can we reproduce it?
This is really important to me.  I can make the repository public if necessary to resolve.

- Do you have log output? Please include between the backticks:

```

[1_Build and Deploy Job (1).txt](https://github.com/microsoft/Oryx/files/12525487/1_Build.and.Deploy.Job.1.txt)

```

**Comment by snehapar9** [comment] 2023-09-05 17:31
Hi @Robotuner,

Thanks for reaching out! I see that the failure may have occurred during platform detection. Would be helpful if you could clarify the following so we can investigate further.

1. Do you have any other information about the repo available? Example - Is it a monorepo? Does it have multiple platforms apart from dotnet 7.0?
2. How is the application being deployed (Portal, CLI) ? Are there steps available so we can reproduce the issue?
3. Are there any additional logs or a similar publicly available repo we could leverage for our investigation?

**Comment by Robotuner** [comment] 2023-09-05 19:03
Thanks for getting back to me. 
My project is a Visual Studio 2022 Uno cross-platform project.  I am only developing for windows and WASM currently, but eventually I will deploy to IOS and Android.  I also have a dot net core api project in the same solution, but that will be hosted on a separate server.  I was unaware of the API feature associated with WASM deployments when I started, so for not, it is not included in the WASM deployment.  

The application is from my  GitHub repository.  The repository is private, but I can add you as a collaborator to give you access (I’ve never added anyone, I assume all I need is an email address). Whatever you need.  

Resolving this is very important to me, and I will provide whatever you need.  I have been looking at this for well over a week, tried different versions of setup-dotnetV#.##, different versions of ***@***.*** (my older project works with ***@***.*** and ***@***.***).  It makes no sense to me that the old project would build and deploy and this project is giving me errors.

I have provided the log of one of the failed builds.  If there is something else I can provide, I will need for you to tell me where to find it.

Thanks for your response.
Lenny

**Comment by Robotuner** [comment] 2023-09-07 16:12
Trying a third time to reply.  The other two time don't seem to be leaving anything in my sent folder.
 
1.  My project is a Uno crossplatform development project with only two (for not) projects, a Windows project and the WASM project that I am having difficulty with.  The two projects are part of a larger solution that includes a dot net core api project.  It is the solution that is in the github repository.
 
2. The WASM project is deployed thru the Azure Static Web apps from a Github workflow action.  The action is attached.
3. I have also attached the entire log from my last attempt.
 
Please let me know if there is anything else I can provide you.  If it will help, I can add you to the collaborator for the github respository so that you can access the code and anything else.
 
Lenny
 
 
 
-----Original Message-----From: "snehapar9" ***@***.***>Sent: Tuesday, September 5, 2023 1:31pmTo: "microsoft/Oryx" ***@***.***>Cc: "Leonard Kong" ***@***.***>, "Mention" ***@***.***>Subject: Re: [microsoft/Oryx] Unable to detect any platform in source directory (Issue #2126)

Hi @Robotuner,
Thanks for reaching out! I see that the failure may have occurred during platform detection. Would be helpful if you could clarify the following so we can investigate further.

Do you have any other information about the repo available? Example - Is it a monorepo? Does it have multiple platforms apart from dotnet 7.0?
How is the application being deployed (Portal, CLI) ? Are there steps available so we can reproduce the issue?
Are there any additional logs or a similar publicly available repo we could leverage for our investigation?

**Comment by snehapar9** [comment] 2023-09-07 17:54
Ah I see, so the platform detection just fails for the WASM project? Can I get access to it?
[Here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) is the documentation to add collaborators.

**Comment by Robotuner** [comment] 2023-09-07 18:50
I have just added you as a collaborator.
 
Thanks.
 
-----Original Message-----

**Comment by snehapar9** [comment] 2023-09-08 08:38
@Robotuner I was able to reproduce this issue. The platform detection could be failing because the `app_location` is `FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist`. It is required for a .csproj file to be present in the source location for Oryx to properly detect dotnet.

I'm still looking into the fix. Will let you know when I have more updates. Thanks for your patience.

**Comment by Robotuner** [comment] 2023-09-08 14:27
Thanks for the update.  This is very odd.  I have another project hosted as azure static web app.  I last built and deployed about three months ago and it worked.  It is:
Pev.engenious.com 
If you want to look at it.

I just went back to look at the build deploy log there.  It actually has the same error messages:

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues
Oryx Version: 0.2.20230501.1, Commit: 58513374525ab2977af68fc5b3c344d32858d8af, ReleaseTagName: 20230501.1
Build Operation ID: dcce475d961db3d1
OS Type           : bullseye
Image Type        : jamstack
Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
---End of Oryx build logs---
Oryx was unable to determine the build steps

Yet it opens.  The only thing I could see is a difference in the Oryx Version: : 0.2.20230501.1

Its possible that comparing that version with the current will help resolve the issue.

Thanks again.

**Comment by Robotuner** [comment] 2023-09-11 19:41
Any updates yet?  I really need to be able to deploy this app.

Thanks

**Comment by snehapar9** [comment] 2023-09-11 20:14
> Any updates yet? I really need to be able to deploy this app. Thanks From: snehapar9 Sent: Friday, September 8, 2023 1:38 AM To: microsoft/Oryx Cc: Leonard Kong; Mention Subject: Re: [microsoft/Oryx] Unable to detect any platform in sourcedirectory (Issue #2126) @Robotuner I was able to reproduce this issue. The platform detection could be failing because the app_location is FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist. It is required for a .csproj file to be present in the source location for Oryx to properly detect dotnet. I'm still looking into the fix. Will let you know when I have more updates. Thanks for your patience. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Thanks for reaching back out. Do you mind sharing the contents of `FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist`? I can run an oryx build against this repo and see if the issue is with detecting platforms in this folder or if it's something else.

**Comment by Robotuner** [comment] 2023-09-11 20:41
I’m not sure what to do.  Didn’t I make you a collaborator to the emailservice repository?  Doesn’t that give you access to EmailService/FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist?

**Comment by snehapar9** [comment] 2023-09-11 20:55
> I’m not sure what to do. Didn’t I make you a collaborator to the emailservice repository? Doesn’t that give you access to EmailService/FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist? From: snehapar9 Sent: Monday, September 11, 2023 1:14 PM To: microsoft/Oryx Cc: Leonard Kong; Mention Subject: Re: [microsoft/Oryx] Unable to detect any platform in sourcedirectory (Issue #2126) Any updates yet? I really need to be able to deploy this app. Thanks From: snehapar9 Sent: Friday, September 8, 2023 1:38 AM To: microsoft/Oryx Cc: Leonard Kong; Mention Subject: Re: [microsoft/Oryx] Unable to detect any platform in sourcedirectory (Issue #2126) @Robotuner I was able to reproduce this issue. The platform detection could be failing because the app_location is FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist. It is required for a .csproj file to be present in the source location for Oryx to properly detect dotnet. I'm still looking into the fix. Will let you know when I have more updates. Thanks for your patience. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***> Thanks for reaching back out. Do you mind sharing the contents of FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist? I can run an oryx build against this repo and see if the issue is with detecting platforms in this folder or if it's something else. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

I was able to build the project and get the contents of EmailService/FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist locally.

Oryx detects platforms from the app_location argument that's provided as an input to the `Azure/static-web-apps-deploy@v1` action and builds it. Since this `app_location` contains only .dll files, Oryx would not be able to perform detection/build.
I'm not sure how scenarios like these are handled while using `Azure/static-web-apps-deploy@v1` action. It would be best to file this issue in the  [static-web-apps](https://github.com/Azure/static-web-apps) repository since they own this action and may have more knowledge on how to approach this scenario.

**Comment by Robotuner** [comment] 2023-09-11 21:00
Are you saying that there isn't anything you can do to help me get this working and that I need to go to azure to get this resolved?

**Comment by snehapar9** [comment] 2023-09-11 21:27
I apologize for the inconvenience but Oryx just detects and builds projects from the `app_location` argument and would expect a .csproj file to be present in the `app_location` to be able to detect and build dotnet solutions.
`app_location` should contain the source code for Oryx to properly detect and build. Please see [this](https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions) document for more information.

**Comment by kubarom** [comment] 2023-12-10 15:50
In my case, manually publishing the Blazor WASM app using `dotnet publish {WebApp.csproj} -o dist` solved my issue. Similarly what's written [here](https://github.com/Azure/static-web-apps/issues/926#issuecomment-1271605017).

**Comment by simonjj** [comment] 2024-01-12 23:32
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.

**Closed by simonjj** 2024-01-12 23:32 UTC
