### ISSUE TITLE
Platform 'php' version '8.0' is unsupported. Supported versions

### ISSUE THREAD

**Issue by ravidigitalway** [microsoft/Oryx#1538] opened 2022-08-29 05:04 UTC
We have updated running application laravel frame work from PHP 7 to PHP 8, it's working fine on local windows and linux susyem , when trying to sync to deployment in azure getting below error.

command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8da884e7257a667 --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20220308.4, Commit: c92fa6a2d6fc14dc9646f80e2bb2e393a5cdc258, ReleaseTagName: 20220308.4

Build Operation ID: |IbHy2OSgLrc=.9062a40f_
Repository Commit : eeb9436bd0536a7c0de045935cc6c8ad0c93a7f5

Detecting platforms...
Error: Platform 'php' version '8.0' is unsupported. Supported versions: 
Error: Platform 'php' version '8.0' is unsupported. Supported versions:\n/bin/bash -c "oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 8.0 -i /tmp/8da884e7257a667 --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log ; exit $PIPESTATUS "

**Comment by qianz2** [comment] 2022-08-30 01:45
Hi @ravidigitalway, thanks for reporting the issue. Can I know what timeframe the issue occurred, is it an intermittent error when you build the app or it's still happening? Oryx supported PHP 8.0 in all images and dynamic installation, oryx recently allow images to pull corresponding debian flavor SDKs from storage account, not sure if it something occurred temporarily when we modified the version files?

**Comment by hvegav** [comment] 2023-04-25 00:37
Did you solve the problem ? I’m having the same issue

**Comment by pauld-msft** [comment] 2023-05-15 16:09
@frivadelaureate - could you provide some more info on this issue?

1. Where are you deploying this (e.g. App Service, Static Web Apps, etc.)?
2. Do you have a simple reproduction that we could use to debug, or perhaps your repo?
3. Do you have any networking rules that could block access to our CDN? https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md#network-dependencies

**Comment by frivadelaureate** [comment] 2023-05-15 16:41
Hi @pauld-msft. Thanks for the response. Here you have more info:
- I'm using a Azure App-service for PHP, but just deploying a static web (HTML & CSS).
- The app-service auto synchronization was working until may-5.
- The repository is in Bitbucket, the webhook still exist and there is no conflict on the main branch.
- Don't have any network restriction.

**Comment by simonjj** [comment] 2024-01-11 22:47
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.

**Closed by simonjj** 2024-01-11 22:47 UTC
