### ISSUE TITLE
deployment failed on visual code python function

### ISSUE THREAD

**Issue by hrana007** [microsoft/Oryx#848] opened 2020-11-12 11:16 UTC
### Bug Report

4:32:56 pm func-integrations-dev-001: Starting deployment...
4:33:01 pm func-integrations-dev-001: Creating zip package...
4:33:01 pm func-integrations-dev-001: Zip package size: 9.56 kB
4:33:08 pm func-integrations-dev-001: Updating submodules.
4:33:08 pm func-integrations-dev-001: Preparing deployment for commit id '3f9bd8da2c'.
4:33:08 pm func-integrations-dev-001: Repository path is /tmp/zipdeploy/extracted
4:33:08 pm func-integrations-dev-001: Running oryx build...
4:33:08 pm func-integrations-dev-001: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
4:33:09 pm func-integrations-dev-001: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
4:33:09 pm func-integrations-dev-001: You can report issues at https://github.com/Microsoft/Oryx/issues
4:33:09 pm func-integrations-dev-001: Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1
4:33:09 pm func-integrations-dev-001: Build Operation ID: |mzUu3HlfM68=.badcf915_
4:33:09 pm func-integrations-dev-001: Repository Commit : 3f9bd8da2c044201898d53079d52b877
4:33:09 pm func-integrations-dev-001: Detecting platforms...
4:34:49 pm func-integrations-dev-001: Error: Oops... An unexpected error has occurred.
4:35:09 pm func-integrations-dev-001: Error: Oops... An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
4:35:20 pm func-integrations-dev-001: Deployment failed.
4:41:05 pm func-integrations-dev-001: Starting deployment...
4:41:11 pm func-integrations-dev-001: Creating zip package...
4:41:11 pm func-integrations-dev-001: Zip package size: 9.56 kB
4:41:16 pm func-integrations-dev-001: Updating submodules.
4:41:16 pm func-integrations-dev-001: Preparing deployment for commit id '454ff6cb3f'.
4:41:16 pm func-integrations-dev-001: Repository path is /tmp/zipdeploy/extracted
4:41:16 pm func-integrations-dev-001: Running oryx build...
4:41:16 pm func-integrations-dev-001: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
4:41:17 pm func-integrations-dev-001: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
4:41:17 pm func-integrations-dev-001: You can report issues at https://github.com/Microsoft/Oryx/issues
4:41:17 pm func-integrations-dev-001: Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1
4:41:18 pm func-integrations-dev-001: Build Operation ID: |hBsCB7s2Qk0=.8513c074_
4:41:18 pm func-integrations-dev-001: Repository Commit : 454ff6cb3f7b486694684c876d9068ea
4:41:18 pm func-integrations-dev-001: Detecting platforms...
4:42:58 pm func-integrations-dev-001: Error: Oops... An unexpected error has occurred.
4:43:18 pm func-integrations-dev-001: Error: Oops... An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
4:43:28 pm func-integrations-dev-001: Deployment failed.

- What happened?

- What did you expect or want to happen?

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```

```

**Comment by davidfmatheson** [comment] 2020-11-13 18:18
It might be the same issue, @qianz2, but I didn't see any timeout errors in @hrana007's output, so I created a new issue.

**Comment by qianz2** [comment] 2021-06-04 07:09
The issue is likely caused by proxy configuration / VPNs. Closing it as it's been long time, feel free to reopen if you have other questions.

**Closed by qianz2** 2021-06-04 07:09 UTC
Labels: Need Information, investigate
