### ISSUE TITLE
Oryx unable to detect .net solution

### ISSUE THREAD

**Issue by bh3605** [microsoft/Oryx#2001] opened 2023-05-23 16:36 UTC
### Bug Report

- What happened?
I'd expect oryx to be able to detect a .net solution and build the solution.

- Do you have log output? Please include between the backticks:

I made sure the directory it was targeting was populated. Hence the first screenshot of me checking the code is where it should be.
![image](https://github.com/microsoft/Oryx/assets/3073436/1e0c9e73-9d16-40f4-926b-ee2e03818eb9)
![image](https://github.com/microsoft/Oryx/assets/3073436/202a7846-37f1-4483-96b1-6c504497bf75)

**Comment by johnholliday** [comment] 2023-05-24 11:14
Getting the same issue.  Thought it might be related to node version upgrade to 16 for GitHub actions, but seems to be a problem with Oryx unable to detect the language.

**Comment by bh3605** [comment] 2023-05-26 14:56
I would've thought this would've been low hanging fruit for them to reply to...

**Comment by daniv-msft** [comment] 2023-05-26 16:06
Thanks for reporting this issue. @waliMSFT, could you please have a look into it?
@bh3605 Just to have all the context, did you run Oryx directly? If not, could you please share the product where this originated (App Service, Static Web Apps, etc.)?

**Comment by bh3605** [comment] 2023-05-26 16:23
I am aware my last two steps aren't going to work, but I'm just messing around with getting Oryx working first.

Azure Devops. Here's my yaml:
```
trigger:
    branches:
        include:
        - master
    paths:
        exclude:
        - azure-pipelines.yml

pool:
    vmImage: ubuntu-latest

jobs:
- job: 
  displayName: Build Application
  container: 'mcr.microsoft.com/oryx/build:latest'
  steps:
    - checkout: self
    - script: echo $(Build.SourcesDirectory)
    - script: cd $(Build.SourcesDirectory) & ls
    - script: oryx build $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dist'
        artifact: 'drop'
        publishLocation: 'pipeline'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        StoreAsTar: true
```

**Comment by waliMSFT** [comment] 2023-05-31 20:05
Hi @bh3605,
Thanks for providing the details. 
Oryx detects the .Net as a platform when it finds a `.csproj` or a `.fsproj` file in the project directory. Based on the screenshot you provided it looks like there is no such files. Hence, Oryx cannot detect the platform (which should be .Net) in this case.

Please let me know if you have any concerns. Thanks

**Comment by pauld-msft** [comment] 2023-05-31 20:17
@bh3605, just want to chip in here and additionally mention that you can likely provide the path to the directory of the web project that you ultimately want to be deployed in app service. So if its `NewHireSchedulerBFF.Core`, perhaps try `oryx build $(Build.SourcesDirectory)/NewHireSchedulerBFF.Core/ --output $(Build.ArtifactStagingDirectory)` and see if its able to detect the dotnet version. 

In theory, we should be looking in sub-directories for the `csproj` as well as long as the `DISABLE_RECURSIVE_LOOKUP` flag isn't enabled, but without access to your repo directly we have not been able to get the exact error you are seeing when working in multi-project solutions. Every time that we try to build we get an ambiguity error that is different than yours:
![image](https://github.com/microsoft/Oryx/assets/107068277/a4a5a55c-6193-4567-a36c-2f4bf5feb4b1)

**Comment by bh3605** [comment] 2023-06-02 18:17
@pauld-msft your response is more useful than your coworker's. I tried that and still no dice. Ultimately, I'm trying to build the service fabric project in the solution. I moved on and got it working through other means. I've seen Oryx unable to resolve nuget packages from private feeds so it feels best to stop trying to use Oryx for now.

Here's what I got when I tried to target one of the cs projects. Same result for a service fabric one.
![image](https://github.com/microsoft/Oryx/assets/3073436/5fb50ec0-5703-4c57-a24d-c440403920c2)

Tried cd into the directory itself before calling `oryx build`. Same thing.
![image](https://github.com/microsoft/Oryx/assets/3073436/dec28e98-297f-4f7e-87b7-b0472190e8ac)

Here's the result trying to build a service fabric project.
![image](https://github.com/microsoft/Oryx/assets/3073436/12ef805b-e0be-44f1-8ecc-fde17b6b77be)

**Comment by pauld-msft** [comment] 2023-06-02 18:39
@bh3605 thanks for the screenshots and tests. Thats quite curious, as we can clearly see the csproj defined in the core project. It would be really helpful if we could reproduce on our end, but since we haven't been able to, I would be interested if manually specifying the language and version to use would allow the build to proceed. For some of our partners, they will be doing this anyways rather than relying on the detection logic.

You can do this with one of the following:
- `oryx build $(Build.SourcesDirectory)/NewHireSchedulerBFF.Core/ --output $(Build.ArtifactStagingDirectory) --platform dotnet --platform-version 7.0`
- `oryx build $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory) --platform dotnet --platform-version 7.0`

You could also attempt to set the `PROJECT` env var to the project file you want to build, as described in the [configuration](https://github.com/microsoft/Oryx/blob/main/doc/configuration.md) docs, since the detection doesn't check for `sfproj` files anyways.

--------------

Either way, glad to hear you were able to enable your scenario, even if it wasn't using Oryx. We will close this issue in a few days if you would not like to explore it any further, unless @johnholliday has some further details or reproduction steps that we would be able to look at.

**Closed** 2023-06-05 14:37 UTC
