### ISSUE TITLE
Installing python 3.9 fails as of 2022-04-06 20:00 EST

### ISSUE THREAD

**Issue by marcboivin** [microsoft/Oryx#1330] opened 2022-04-07 00:10 UTC
Been deploying all day, everything was fine. 

Now 

```
8:02:56 PM: Creating resource group "egrspmail" in location "East US"...
8:02:57 PM: Successfully created resource group "egrspmail".
8:02:57 PM: Ensuring App Service plan "ASP-egrspmail-e5de" exists...
8:02:57 PM: Creating App Service plan "ASP-egrspmail-e5de"...
8:03:03 PM: Successfully created App Service plan "ASP-egrspmail-e5de".
8:03:03 PM: Creating storage account "egrspmail" in location "East US" with sku "Standard_LRS"...
8:03:26 PM: Successfully created storage account "egrspmail".
8:03:26 PM: Verifying that Application Insights is available for this location...
8:03:27 PM: Creating Application Insights resource "egrspmail"...
8:03:29 PM: Successfully created Application Insights resource "egrspmail".
8:03:29 PM: Creating new function app "egrspmail"...
8:03:50 PM: Successfully created function app "egrspmail": https://egrspmail.azurewebsites.net
8:03:51 PM egrspmail: Starting deployment...
8:03:54 PM egrspmail: Creating zip package...
8:03:54 PM egrspmail: Zip package size: 3.11 kB
8:03:55 PM egrspmail: Fetching changes.
8:03:56 PM egrspmail: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/75756aea-deb8-4d2e-b3e2-1799f6e854c8.zip (0.00 MB) to /tmp/zipdeploy/extracted
8:03:58 PM egrspmail: Updating submodules.
8:03:59 PM egrspmail: Preparing deployment for commit id 'f33351b2-1'.
8:04:00 PM egrspmail: PreDeployment: context.CleanOutputPath False
8:04:00 PM egrspmail: PreDeployment: context.OutputPath /home/site/wwwroot
8:04:00 PM egrspmail: Repository path is /tmp/zipdeploy/extracted
8:04:00 PM egrspmail: Running oryx build...
8:04:00 PM egrspmail: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
8:04:02 PM egrspmail: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
8:04:02 PM egrspmail: You can report issues at https://github.com/Microsoft/Oryx/issues
8:04:02 PM egrspmail: Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
8:04:02 PM egrspmail: Build Operation ID: |Y3IFSOH9JFQ=.c73b08f6_
8:04:02 PM egrspmail: Repository Commit : f33351b2-1173-4fd8-9227-6553120438c9
8:04:02 PM egrspmail: Detecting platforms...
8:04:04 PM egrspmail: Detected following platforms:
8:04:04 PM egrspmail:   python: 3.9.12
8:04:04 PM egrspmail: Version '3.9.12' of platform 'python' is not installed. Generating script to install it...
8:04:04 PM egrspmail: Source directory     : /tmp/zipdeploy/extracted
8:04:04 PM egrspmail: Destination directory: /home/site/wwwroot
8:04:04 PM egrspmail: Downloading and extracting 'python' version '3.9.12' to '/tmp/oryx/platforms/python/3.9.12'...
8:04:05 PM egrspmail: Downloaded in 1 sec(s).
8:04:05 PM egrspmail: Verifying checksum...
8:04:06 PM egrspmail: Extracting contents...
8:04:11 PM egrspmail: Done in 7 sec(s).
8:04:11 PM egrspmail: Python Version: /tmp/oryx/platforms/python/3.9.12/bin/python3.9
8:04:11 PM egrspmail: Running pip install...
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
8:04:11 PM egrspmail: Done in 0 sec(s).
8:04:13 PM egrspmail: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
8:04:13 PM egrspmail: Deployment Failed.
8:04:20 PM egrspmail: Deployment failed.
```

This is a new deployment but pushing to my existing function has the exact same behaviour 

```
7:59:40 PM egrmail: Starting deployment...
7:59:42 PM egrmail: Creating zip package...
7:59:42 PM egrmail: Zip package size: 3.11 kB
7:59:43 PM egrmail: Fetching changes.
7:59:44 PM egrmail: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/3fe2b7e6-6030-420e-8e10-c9b7da0fd79c.zip (0.00 MB) to /tmp/zipdeploy/extracted
7:59:46 PM egrmail: Updating submodules.
7:59:47 PM egrmail: Preparing deployment for commit id '7529d7d4-d'.
7:59:47 PM egrmail: PreDeployment: context.CleanOutputPath False
7:59:47 PM egrmail: PreDeployment: context.OutputPath /home/site/wwwroot
7:59:47 PM egrmail: Repository path is /tmp/zipdeploy/extracted
7:59:47 PM egrmail: Running oryx build...
7:59:47 PM egrmail: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
7:59:50 PM egrmail: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
7:59:50 PM egrmail: You can report issues at https://github.com/Microsoft/Oryx/issues
7:59:50 PM egrmail: Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
7:59:50 PM egrmail: Build Operation ID: |rvLj0pYNsn0=.a981bb2b_
7:59:50 PM egrmail: Repository Commit : 7529d7d4-d210-49a4-840f-1f01e4566a51
7:59:50 PM egrmail: Detecting platforms...
7:59:51 PM egrmail: Detected following platforms:
7:59:51 PM egrmail:   python: 3.9.12
7:59:51 PM egrmail: Version '3.9.12' of platform 'python' is not installed. Generating script to install it...
7:59:51 PM egrmail: Source directory     : /tmp/zipdeploy/extracted
7:59:51 PM egrmail: Destination directory: /home/site/wwwroot
7:59:51 PM egrmail: Downloading and extracting 'python' version '3.9.12' to '/tmp/oryx/platforms/python/3.9.12'...
7:59:52 PM egrmail: Downloaded in 1 sec(s).
7:59:52 PM egrmail: Verifying checksum...
7:59:53 PM egrmail: Extracting contents...
7:59:57 PM egrmail: Done in 6 sec(s).
7:59:57 PM egrmail: Python Version: /tmp/oryx/platforms/python/3.9.12/bin/python3.9
7:59:57 PM egrmail: Running pip install...
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
7:59:57 PM egrmail: Done in 0 sec(s).
7:59:59 PM egrmail: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
7:59:59 PM egrmail: Deployment Failed.
8:00:06 PM egrmail: Deployment failed.
```

**Comment by LaBarreOksnee** [comment] 2022-04-07 02:25
Agreed. Started around 2:00 PM PDT. I've tried rebuilding the App Service, installing locally after manually building my virtualenv (which works btw). I tried a manual build of the application (Django) but getting an unrelated database is locked on an empty sqlite3 file...don't feel like troubleshooting that after spending all day trying to get this to work. 

I may try to downgrade to Python 3.8 tomorrow...but I can afford to, because the app is so small.

Python Version: /tmp/oryx/platforms/python/3.9.12/bin/python3.9
Creating directory for command manifest file if it doesnot exist
/tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
Removing existing manifest file
/tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
Python Virtual Environment: antenv
Creating virtual environment...
/tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)\n/tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da183a02e21589 --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log

**Comment by danialasghar** [comment] 2022-04-07 02:44
Had the same issue all evening today. 

Downgrading to 3.8 fixed it.

**Comment by mahalel** [comment] 2022-04-07 03:07
Hi, I am also having this issue on 3.9 today. I tried deleting the function, redeploying it and publish it again (from a devcontainer) and I get the same issue.

Reprovisioned the function with python3.8 and redeployed it and that seems to work ok.

**Comment by LaBarreOksnee** [comment] 2022-04-07 03:59
Thank you! Confirmed. I downgraded the application to 3.8, created a new GitHub auto-deploy (to be sure it was invoking 3.8), and everything worked.

**Comment by svaidyans** [comment] 2022-04-07 07:34
Having the same issue with Python 3.9 and App Service on VS Code 1.65.2:

12:58:41 PM testapilite: Starting deployment...
12:58:53 PM testapilite: Creating zip package...
12:58:53 PM testapilite: Zip package size: 6.35 kB
12:58:56 PM testapilite: Fetching changes.
12:58:57 PM testapilite: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/24ea4bb9-f124-4481-a187-e0520e8f3244.zip (0.01 MB) to /tmp/zipdeploy/extracted
12:59:10 PM testapilite: Updating submodules.
12:59:12 PM testapilite: Preparing deployment for commit id 'f87f202e-8'.
12:59:12 PM testapilite: Repository path is /tmp/zipdeploy/extracted
12:59:12 PM testapilite: Running oryx build...
12:59:12 PM testapilite: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da18684febab2a --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
12:59:14 PM testapilite: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
12:59:14 PM testapilite: You can report issues at https://github.com/Microsoft/Oryx/issues
12:59:14 PM testapilite: Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1
12:59:14 PM testapilite: Build Operation ID: |d6JGacCiD70=.a2bbfd4f_
12:59:14 PM testapilite: Repository Commit : f87f202e-807b-4376-bbed-833ec3954af3
12:59:14 PM testapilite: Detecting platforms...
12:59:15 PM testapilite: Detected following platforms:
12:59:15 PM testapilite:   python: 3.9.12
12:59:15 PM testapilite: Version '3.9.12' of platform 'python' is not installed. Generating script to install it...
12:59:16 PM testapilite: Using intermediate directory '/tmp/8da18684febab2a'.
12:59:16 PM testapilite: Copying files to the intermediate directory...
12:59:17 PM testapilite: Done in 0 sec(s).
12:59:17 PM testapilite: Source directory     : /tmp/8da18684febab2a
12:59:17 PM testapilite: Destination directory: /home/site/wwwroot
12:59:17 PM testapilite: Downloading and extracting 'python' version '3.9.12' to '/tmp/oryx/platforms/python/3.9.12'...
12:59:17 PM testapilite: Downloaded in 1 sec(s).
12:59:17 PM testapilite: Verifying checksum...
12:59:17 PM testapilite: Extracting contents...
12:59:26 PM testapilite: performing sha512 checksum for: python...
12:59:26 PM testapilite: Done in 10 sec(s).
12:59:26 PM testapilite: Python Version: /tmp/oryx/platforms/python/3.9.12/bin/python3.9
12:59:26 PM testapilite: Creating directory for command manifest file if it doesnot exist
12:59:26 PM testapilite: Removing existing manifest file
12:59:27 PM testapilite: Python Virtual Environment: antenv
12:59:27 PM testapilite: Creating virtual environment...
12:59:27 PM testapilite: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
12:59:27 PM testapilite: /tmp/oryx/platforms/python/3.9.12/bin/python3.9: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /tmp/oryx/platforms/python/3.9.12/lib/libpython3.9.so.1.0)
12:59:29 PM testapilite: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da18684febab2a --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
12:59:30 PM testapilite: Deployment Failed.
12:59:42 PM testapilite: Deployment failed.

**Comment by benbuo** [comment] 2022-04-07 08:36
Hi @mahalel I don't think that 'general' tab appears if the function is created under 'consumption' plan? Is there another way to do it do you know?

**Comment by jjnanthakumar** [comment] 2022-04-07 09:25
I am also facing this issue today while deploying Python Application in Azure App Service.

Please fix this ASAP because this package is used by Most Azure Resources.

**Comment by jjnanthakumar** [comment] 2022-04-07 09:26
> I am also facing this issue today while deploying Python Application in Azure App Service.
> 
> Please fix this ASAP because this package is used by Most Azure Resources.

Also, I can't downgrade to Python 3.8 because I have used some build-in packages which are not available in Python 3.8

**Comment by vrdmr** [comment] 2022-04-07 09:31
@all - Apologies for hitting this issue. I am trying to get this unlocked and get the right people involved. Will have an update asap.

**Comment by pietz** [comment] 2022-04-07 11:26
> Hi @mahalel I don't think that 'general' tab appears if the function is created under 'consumption' plan? Is there another way to do it do you know?

Also, why wouldn't this option be available in the consumption plan? Changing the runtime or the version seems not related.

**Comment by cloudlessdreams** [comment] 2022-04-07 12:25
Could there be a mismatch between the container (Debian Stretch) and the Azure Function Python environment (Buster)? @vrdmr

**Comment by ismaan1998** [comment] 2022-04-07 12:29
> @BartoszLulka @benbuo I did it via the Azure CLI:
> 
> ```
> az functionapp config set --name <FUNCTION_APP> \
> --resource-group <RESOURCE_GROUP> \
> --linux-fx-version <LINUX_FX_VERSION>
> ```
> 
> Where `--linix-fx-version "Python|3.8` Per: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Cazurecli-linux%2Capplication-level#changing-python-version

its --linux-fx-version "python|3.8"

**Comment by cloudlessdreams** [comment] 2022-04-07 12:35
> Had the same issue all evening today.
> 
> Downgrading to 3.8 fixed it.

Very fast fix! Appreciate you.

**Comment by RadekNov** [comment] 2022-04-07 13:10
Have the same issue with Python 3.9 but I can't use lower version because of usage of packages that are compatible only with 3.9 and newer. On the other side 3.10 seems not to be supported by azure function so I need fix this issue ASAP

**Comment by hf-kklein** [comment] 2022-04-07 13:16
Having the same issue.

**Comment by cormacpayne** [comment] 2022-04-07 13:28
Hey folks, apologies for the breaking changes that this issue has caused for your applications.

Oryx has pre-installed Python SDKs on the build images; if the SDK that your application is targeting is not a part of this set, Oryx will fallback to dynamic installation, which attempts to pull a Python SDK that meets your application's requirements from our storage account, where we backup a variety of Python SDKs.

In this case, it appears that the Python 3.9.12 SDK was published to our storage account yesterday around 3:10 PM PST (10:10 PM UTC), and applications targeting Python 3.9 are now pulling down this 3.9.12 SDK rather than the previously published 3.9.7 SDK.

I'm optimistic that we should have this resolved in the next couple of hours, but in the meantime, as folks have mentioned above, if you are able to downgrade your application to using Python 3.8, please consider doing so. Alternatively, if your build/deployment method allows you to snap to a specific _patch_ version of Python, please consider targeting Python 3.9.7, which was the previous 3.9.* version that can be pulled down during dynamic installation.

Again, apologies for the issues that this has caused you all.

**Comment by r44v** [comment] 2022-04-07 13:35
Glad there is a fix on the way.

I would like to point out this also effects the vscode deploy using the azure function extension (which is probably just a wrapper around the remote deploy api), this results in the following error.
```
Error: request to https://xxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
```

**Comment by cloudlessdreams** [comment] 2022-04-07 15:15
> Hey folks, the Python 3.9.12 SDK has been removed from our storage account and is no longer available to use for dynamic installation; Python apps targeting 3.9 should now be pulling the 3.9.7 SDK as they were before. Please feel free to try and build/deploy your Python application again and let us know if you're still seeing the issue.
> 
> You may continue to see this issue for a little bit longer (< 1 hour) due to our CDN cache needing to be cleared, but I'm hopeful that folks targeting Python 3.9 for their application will no longer be blocked shortly after.
> 
> I'll monitor the status of this for the next hour or so and once things look to be in a stable state, I'll close this issue. Thanks again for your patience and understanding.

Great work!

**Comment by bandhit** [comment] 2022-04-07 15:18
> Hey folks, the Python 3.9.12 SDK has been removed from our storage account and is no longer available to use for dynamic installation; Python apps targeting 3.9 should now be pulling the 3.9.7 SDK as they were before. Please feel free to try and build/deploy your Python application again and let us know if you're still seeing the issue.
> 
> You may continue to see this issue for a little bit longer (< 1 hour) due to our CDN cache needing to be cleared, but I'm hopeful that folks targeting Python 3.9 for their application will no longer be blocked shortly after.
> 
> I'll monitor the status of this for the next hour or so and once things look to be in a stable state, I'll close this issue. Thanks again for your patience and understanding.

Thank you very much!
I confirm that I be able to perform remote build with 3.9.7.

**Comment by cormacpayne** [comment] 2022-04-07 17:36
I'm going to close this issue as it seems Python 3.9 builds are now working as intended with the 3.9.7 binaries in our storage account. Please feel free to comment on this issue if the problem arises again and we'll take a look as soon as possible. Thanks again for everyone's patience and understanding!

**Closed by cormacpayne** 2022-04-07 17:36 UTC

**Comment by cormacpayne** [comment] 2022-11-10 17:29
@dkreeft Hey there, would you mind providing the logs from your unsuccessful build? The latest version of Python that Oryx supports, 3.7.12, was published back in August, so the above issue shouldn't be related, but I would be interested in taking a look at your logs to see if we can pinpoint the root cause and ensure it's not occurring for other users.

**Comment by dkreeft** [comment] 2022-11-11 08:49
@cormacpayne thanks a lot. I have opened a separate issue to keep things clean in here: https://github.com/microsoft/Oryx/issues/1678

**Comment by XariZaru** [comment] 2025-05-28 23:57
> [@dkreeft](https://github.com/dkreeft) Hey there, would you mind providing the logs from your unsuccessful build? The latest version of Python that Oryx supports, 3.7.12, was published back in August, so the above issue shouldn't be related, but I would be interested in taking a look at your logs to see if we can pinpoint the root cause and ensure it's not occurring for other users.

I've come across a very similar issue while working with Python 3.11. My Web App is also set up as a 3.11 Python stack. 

```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 8.2 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dd9e419701a179 | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20250107.1+ef3fb2f9c490a4fbb1f76b5746cd4ba2ff0409f4, Commit: ef3fb2f9c490a4fbb1f76b5746cd4ba2ff0409f4, ReleaseTagName: 20250107.1

Build Operation ID: d6cd41529c64a964
Repository Commit : 1a4e0510-19ba-4ab7-a483-a8a753288132
OS Type           : bullseye
Image Type        : githubactions

Detecting platforms...
Detected following platforms:
  python: 3.8.20
Version '3.8.20' of platform 'python' is not installed. Generating script to install it...
Error: Couldn't detect a version for the platform 'php' in the repo.
Error: Couldn't detect a version for the platform 'php' in the repo.\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 8.2 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dd9e419701a179 | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
 ```
