### ISSUE TITLE
Could not build wheels for , since package 'wheel' is not installed.

### ISSUE THREAD

**Issue by minhphan88** [microsoft/Oryx#587] opened 2020-05-13 16:30 UTC
### Bug Report

- At what date and time did you most recently experience the problem?
13/05/2020- 13:12:45( London )

- Where did you experience the problem? AZURE WEB APPS

- If your repo is publicly available please share its URL:

- What happened?

I was using CI/CD build for an Azure Web Apps. 
I tried to include nlpk, sklearn and other packages in the requirements.txt
However, after upgrading pip those packaged can't bt built because of "wheel is not installed".
I even tried to include wheel in requirements.txt.

- What did you expect or want to happen?

Building wheels for collected packages: nltk, sklearn
  Building wheel for nltk (setup.py): started
  Building wheel for nltk (setup.py): finished with status 'done'

- How can we reproduce it?
please include in Oryx after upgrading pip.

python -m pip install --upgrade pip setuptools wheel

- Do you have log output? Please include between the backticks:

```
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.1
Done in 3 sec(s).
Running pip install...
[13:12:35+0000] Collecting wheel
[13:12:35+0000]   Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
[13:12:35+0000] Collecting nltk
[13:12:35+0000]   Downloading nltk-3.5.zip (1.4 MB)
[13:12:36+0000] Collecting sklearn
[13:12:36+0000]   Downloading sklearn-0.0.tar.gz (1.1 kB)
[13:12:45+0000] Could not build wheels for nltk, since package 'wheel' is not installed.
[13:12:45+0000] Could not build wheels for sklearn, since package 'wheel' is not installed.
[13:12:45+0000] Could not build wheels for setuptools, since package 'wheel' is not installed
```

**Comment by kichalla** [comment] 2020-05-18 13:06
@minhphan88 Which `region` are you deploying your app to? I was not able to repro this issue when I tried on the `West US 2` region. Also could you share your `requirements.txt` file? For example, when I tried with the following, I was not able to reproduce the issue:

```
click==6.7
Flask==1.0.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.1
Werkzeug==0.14.1
nltk
sklearn

```

**Comment by minhphan88** [comment] 2020-05-18 13:17
@kichall: it's in UK south,
In addition, I forgot to mention that I couldn't set the GITHUB_WORKSPACE variable and I received the following warning:

Upgrading pip...
WARNING: The directory '/github/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

This could be the reason for the error. I couldn't find any documentation regarding changing the default GITHUB_WORKSPACE variable while using Oryx to build the app.

Thanks so much

**Comment by kichalla** [comment] 2020-05-18 13:34
> This could be the reason for the error. I couldn't find any documentation regarding changing the default GITHUB_WORKSPACE variable while using Oryx to build the app.

So are you longer seeing this issue? Yeah I am not familiar with `GITHUB_WORKSPACE` variable and is probably related to Azure App Service (it uses Oryx for building apps). I would suggest to read their docs.

**Comment by minhphan88** [comment] 2020-05-19 08:45
@kichalla  thanks for that. However, there's no option to manipulate GITHUB_WORKSPACE in the build. Hence I think that could be a bug.

**Comment by kichalla** [comment] 2020-11-11 11:13
Closing this issue as we are not able to reproduce it. Feel free to reopen it with additional details.

**Closed by kichalla** 2020-11-11 11:13 UTC
Labels: External, investigate
